### ISSUE TITLE
How to install ?

### ISSUE THREAD

**Issue by tonai** [apiel/test-crawler#1]
Hi,
your tool look very nice.
I wanted to test it and I tried `npx test-crawler` as suggested in your doc, unfortunately I got the following error:
```
Downloading Chromium r669486 - 347.1 Mb [====================] 100% 0.0s 
info sharp Using cached [HOME]/.npm/_libvips/libvips-8.7.4-linux-x64.tar.gz
[HOME]/.npm/_npx/20761/bin/test-crawler: ligne 11: isomor-server : commande introuvable
```

Here are my plateform informations:
* Ubuntu 18.04
* node 12.4.0
* npm 6.9.0

Do you have any suggestion ?

**Comment by apiel** [comment]
Did you first run `yarn add test-crawler` (or npm install test-crawler) to add it to your project?

**Comment by tonai** [comment]
Hum no.
As you can crawl pages by giving URLs I thought it was a standalone project and you can use it independently.

I can try to install it as a dependency on a project, but how to I open the UI ?

**Comment by apiel** [comment]
So you have to options, the one from the doc:
```
yarn add test-crawler
npx test-crawler
```
And then you open the url http://127.0.0.1:3005/
You can even run this in a separate project, to have it standalone,

The other option is to clone the repo:
```
git clone https://github.com/apiel/test-crawler.git
./test-crawler/packages/test-crawler-ui/test-crawler
``` 
or
```
git clone https://github.com/apiel/test-crawler.git
cd test-crawler
npx lerna bootstrap # this might not be necessary
cd packages/test-crawler-ui
yarn prod
``` 
Unfortunatelly, right now I don't have so much time to make some change but feel free to ask question or to propose features, I will do my best to improve this project ;-)

**Comment by tonai** [comment]
Thanks for your reply.
Launching the two commands `yarn` + `npx` works.
I'm not used to `yarn` so I was thinking the two commands was doing the same thing.
I only use `npx` with `create-react-app` and it does not require a `yarn` command hence my confusion.
But thanks again for your explanation :)
