### ISSUE TITLE
Running 'npx test-crawler' gives error "The system cannot find the path specified"

### ISSUE THREAD

**Issue by abishekpadaki** [apiel/test-crawler#2]
Node Version: 12.9.0

Running the command `npx test-crawler` resulted in the error 

> The system cannot find the path specified.

Did not see any prerequisite steps mentioned in the docs before running this command apart from the package's installation

**Comment by apiel** [comment]
Thanks for the report. I made an update few days ago and it might have brake it (but actually Travis didn't report anything). Anyhow, I will get a look at it as soon as possible (hopefully I will have time today). Also I wanted to review the documentation and find a way to make the setup easier.

**Comment by apiel** [comment]
Now it should be easier to install. Try:
```
yarn global add test-crawler
test-crawler
```
Let me know if it is working. Thx
